on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      force:
        description: "Enter 'force' if you want to force a refresh"
        required: false
        default: ''

name: Update bucket
jobs:
  excavate:
    name: Excavator
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavator
        uses: Ash258/Scoop-GithubActions@stable-win
        env:
          GITH_EMAIL: herouucn@foxmail.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: '1'