on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      force:
        description: "Enter 'force' if you want to force a refresh"
        required: false
        default: ''

name: Update bucket
jobs:
  update:
    name: ♻ Update manifests
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@master
      - name: ♻ Run autoupdate
        uses: foosel/scoop-checkver-action@main
        with:
          bucket: bucket
          force: ${{ github.event.inputs.force }}
      - uses: EndBug/add-and-commit@v7
        with:
          message: "chore: Update package version"
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'